command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: SERVING_ENDPOINT
    value: acao-bakehouse-advisor-llm
  - name: GENIE_SPACE_ID
    value: "01f1287adb6b14dbbb0beb9efddd4a4d"
  - name: VS_INDEX_METADATA
    value: "acao_bakehouse_advisor_catalog.default.metadata_vs_index"
  - name: VS_INDEX_KNOWLEDGE
    value: "acao_bakehouse_advisor_catalog.default.kb_vs_index"
  - name: PGHOST
    value: "ep-shy-darkness-d2ksks1a.database.us-east-1.cloud.databricks.com"
  - name: PGPORT
    value: "5432"
  - name: PGDATABASE
    value: "acao_bakehouse_advisor_sessions"
  - name: PGUSER
    value: "3131fa31-e399-41ff-a2a8-dd7aa3cb5bef"
  - name: LAKEBASE_INSTANCE
    value: "acao-bakehouse-advisor-sessions"
